### ISSUE TITLE
Revision

### ISSUE THREAD

**Issue by LachoCardenas44** [LachoCardenas44/ProyectoFinal_AC#1]
Profe acabo de actualizar el proyecto , anteriormente solo mostraba hasta la posición 14 de la serie Fibonacci debido a que usé registros de 8 bits , y el máximo número q almacenan es 255 , así q el máximo número de la serie que podía almacenar era precisamente la.posicion 14 

Ahora lo mejoré para q muestre hasta la posición 24 , estas limitaciones son inevitables debido a la capacidad máxima de los registros , podría seguir haciendo mejoras para mostrar más posiciones pero creo q como está ya cumple con lo pedido 

Muchas Gracias 

Quisiera exponer mi proyecto para explicar y mostrar que sé lo que hice pero bueno , la decisión general fue que no se expusiera.

**Comment by yosbel-penate** [comment]
buen trabajo...
